version: "3.9"
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes: 
      - ./init_clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - "./clickhouse_data:/var/lib/clickhouse" 
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_USER: click
      CLICKHOUSE_PASSWORD: click

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      start_period: 10s
      retries: 20
      interval: 10s

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    depends_on:
      - zookeeper
    ports:
      - '9095:9095'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9095
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]

      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  kafka-setup:
      image: confluentinc/cp-kafka:7.3.0
      depends_on:
        kafka:
          condition: service_healthy
      restart: on-failure
      entrypoint: [ "/bin/bash", "-c" ]
      command: |
        "
        echo 'Ожидание готовности Kafka...'
        while ! kafka-topics --bootstrap-server kafka:9092 --list; do
          sleep 1
        done

        echo 'Создание топика...'
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic clickhouse --partitions 3 --replication-factor 1 --config retention.ms=604800000

        echo 'Топик успешно создан:'
        kafka-topics --bootstrap-server kafka:9092 --list
        "

  akhq:
    image: tchiotludo/akhq
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"

  state_stats_calculator:
    build: ./state_stats_calculator
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    environment:
      KAFKA_BROKER: "kafka:9092"
      TOPIC_NAME: "clickhouse"
      CLICKHOUSE_HOST: "clickhouse"
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: "click"
      CLICKHOUSE_PASSWORD: "click"
      PATH_TO_DATA: "/app/data/transactions.csv"
      OUTPUT_PATH: "/app/output/transactions_stats_by_states.csv"
      BATCH_SIZE: 1024
    depends_on:
      - clickhouse
      - kafka
      - kafka-setup

